### ISSUE TITLE
Front - The columns size isn't equal to 12

### ISSUE THREAD

**Issue by hotgeart** [kdion4891/valiant#1]
![](https://i.imgur.com/LItttsP.png)

https://github.com/kdion4891/valiant/blob/6a69b28aaedf9dbaccba07b5950e842c38bfc76e/resources/views/inputs/list.blade.php

**Comment by kdion4891** [comment]
It was made this was on purpose. I find it more aesthetically pleasing, especially on wide screens. Would love to hear your thoughts, this is a very easy fix if people think it’s ugly.

**Comment by hotgeart** [comment]
You seem to have an old version of AdminLTE (Bootstrap 3). With Bootstrap 4.4 you can change the container according to the breakpoints. https://getbootstrap.com/docs/4.4/layout/overview/#containers

You could have `.container-xl` to have your container fluid until it's really to big.

preview :

![](https://i.imgur.com/xvIGnRE.png)

But for the index page (with datatable) I kind of like the full width. So may be pass a variable to layouts/auth.blade.php if you want a `.container-fluid` for the pages with datatable or a `.container-xl` for the pages with just a form.

**Comment by kdion4891** [comment]
This could be a config option. 

Also this uses adminlte 3 which is the newest version of adminlte.
