### ISSUE TITLE
Making field optional on listing screen?

### ISSUE THREAD

**Issue by seongbae** [kdion4891/valiant#11]
Hi,

I created a relationship between two models but it is optional.  For example, when creating a model called article, it has a category field which is optional.  But if I create an article without category, on the article listing screen, it's looking for category.name.  How can I make the category field optional on the article listing screen?

Thanks!

**Comment by kdion4891** [comment]
Just add `withDefault(['name' => null])` to your `belongsTo` relationship.

**Comment by seongbae** [comment]
That worked. Thank you!
