### ISSUE TITLE
How to filter data

### ISSUE THREAD

**Issue by seongbae** [kdion4891/valiant#12]
Is there a way to filter data on the listing screen? For example, I want to show only entries created by me.

**Comment by mustafa-online** [comment]
Looking for that too

**Comment by seongbae** [comment]
I made some updates to ValiantController and ValidantModel to make this work. I can submit PR if you want.

**Comment by kdion4891** [comment]
Yeah I was going to get around to adding filters as a feature, have just been busy with work. I'd imagine they would work similar to the bulk dropdown. Feel free to submit a PR so I can have a look.

**Comment by kdion4891** [comment]
For now you can use global model scopes.

**Comment by seongbae** [comment]
Thanks! I did and it's working good.
