### ISSUE TITLE
Add default value to an input field?

### ISSUE THREAD

**Issue by seongbae** [kdion4891/valiant#14]
Is there a way to add a default value to input fields?  I saw the Field class and input() only accepts field type.  Maybe we can add an optional second parameter that accepts default value..?

**Comment by kdion4891** [comment]
You can simply add the default value to your model for any attribute you want.

**Comment by seongbae** [comment]
On the server side, yes, but not on the client side.  For example, for a date field, I want to have it default to today's date on the form.  Even though we can set the default value when saving a model, users don't know that and they will still try to set the value which takes more time to fill out forms.

**Comment by kdion4891** [comment]
Try adding to your model class:

```
protected $attributes = [
        'my_date' => now(),
    ];
```

If you want to submit a PR with a new `inputDefault()` method for inputs and update the view for the input field, I will merge.

**Comment by seongbae** [comment]
Thanks @kdion4891!  That didn't work because attributes doesn't allow you to set default value dynamically.  In such case, you have to set it in constructor. Below worked for me:

```
public function __construct(array $attributes = [])
    {
        $this->my_date = date('Y-m-d');
        parent::__construct($attributes);
    }
```
