### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by hotgeart** [kdion4891/valiant#4]
Hi,

Some suggestions for future releases.

## 1. Prefix

By default /admin could be changed via .env

## 2. Translation

More websites are now multilingual. I really like the implementation on [Twill](https://twill.io/docs/) with laravel-translatable.

https://github.com/Astrotomic/laravel-translatable

## 3. Add the the doc a "join" example

I'm lost on how can I easly join model. May be add an example in the doc or a repo example for a blog with articles and categories. How to select a categories when I create/edit an article.

Again its just suggestions, I don't know your plan for this package, if you want to keep it small or not.

**Comment by kdion4891** [comment]
There is a relationship example in the docs: https://github.com/kdion4891/valiant/blob/master/docs/examples.md

Translations are a good idea but added a bit extra overhead for me that I didn't have time for.

The prefix is also a good idea.

**Comment by hotgeart** [comment]
Yeah may be for a 2.0 :D

**Comment by mustafa-online** [comment]
@kdion4891 , Does this panel have **Filters** built in?

**Comment by kdion4891** [comment]
No it does not. I may add it in the near future. For now you can easily add your own dropdown view file to your indexActions.
