### ISSUE TITLE
Models Not Populating

### ISSUE THREAD

**Issue by TheZachh** [kdion4891/valiant#5]
First of all, this is a brilliant package. I've been waiting for something like it to come along. Found it on Reddit. Thank you!

My issue is that when I create a model (in my case: Task) and then subsequently try to create a new Task, the views don't reflect anything in the tables.

The Tasks table is empty, but when I look in PHPMyAdmin, I can see the data in the Tasks table.  

Same is true for the native models -- Users view shows nothing even after creating one. 

I've tried clearing caches and restarting the server, but no dice. This is a fresh install of Valiant on a freshly installed test project of Laravel 6.

Is there something I'm missing or is this indeed a bug with the package? 

Thank you for any advice!

**Comment by TheZachh** [comment]
![ValiantIssue](https://user-images.githubusercontent.com/19249281/71633047-89516f80-2bd7-11ea-9735-f3f5514727dc.png)

**Comment by kdion4891** [comment]
Make sure you set the correct app URL in your `.env` file

Also check the chrome console / network tab for errors

**Comment by JochemKlingeler** [comment]
I had this same problem, instead of using 127.0.0.1:8000, I used localhost:8000 (as discribed in .env) and then they showed up.

**Comment by kdion4891** [comment]
I'm going to be pushing a change to address this so that the table ID's are not reliant upon the app config URL.

**Comment by TheZachh** [comment]
Ok, I changed from http://localhost  to APP_URL=http://127.0.0.1:8000 and now the models load. Looking forward to that dependency change. Never would have figured that out to be the problem. Thank you! :)

**Comment by kdion4891** [comment]
This is now fixed in version 1.0.1.
