### ISSUE TITLE
Error on Login!

### ISSUE THREAD

**Issue by mustafa-online** [kdion4891/valiant#8]
Undefined class constant 'App\Providers\RouteServiceProvider::HOME'
..........
![va](https://user-images.githubusercontent.com/5323832/72220172-a3d00500-3556-11ea-98d4-c8c6081456f8.PNG)

**Comment by kdion4891** [comment]
Did you install a clean version of Laravel 6 or are you trying to add this to an existing project?

`RouteServiceProvider` should contain this constant:

`public const HOME = '/home';`

**Comment by mustafa-online** [comment]
Yes It's a fresh installation (Laravel v6), there is no such Constant!
I solve the issue by editing **loginController** :

 protected $redirectTo = '/home';

**Comment by kdion4891** [comment]
Glad you figured it out.
