### ISSUE TITLE
How to add user_id as field?

### ISSUE THREAD

**Issue by seongbae** [kdion4891/valiant#9]
Thanks for the awesome tool.  I'm building a small application using your tool and had a question.  I have a user_id field in a table as a foreign key. I'd usually use Auth::id() to automatically assign the id but wasn't sure where to add it in the valiant field area for a model.

**Comment by kdion4891** [comment]
Use a model observer and add the Auth user_id on ‘creating’

**Comment by seongbae** [comment]
Got it. Thanks!
